# Note if you are trying to deploy on vps then directly fill values in ("")

from os import getenv

# VPS --- FILL COOKIES 🍪 in """ ... """ 

INST_COOKIES = """
# wtite up here insta cookies
"""

YTUB_COOKIES = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.youtube.com	TRUE	/	FALSE	1750034876	_gcl_au	1.1.2102470221.1742258876
#HttpOnly_.youtube.com	TRUE	/	TRUE	1776819168	__Secure-3PSID	g.a000uwg-dTwP1twnccQTKvS64x87qy2Q1UOqA_FnWnCbF9ZhBVnFult-Hy56jbwaYSO-6ODnXQACgYKAU0SARISFQHGX2MiyZAaxVSZEcma888rr6aYnRoVAUF8yKrm83Hi5GMRybEDBZpsPQwA0076
.youtube.com	TRUE	/	FALSE	1774742059	SIDCC	AKEyXzWKKzwxL5ghfNhL6GtWimGw-NRC3GGZCX2Q-m3VWMUxIufwPARL8VBVD6ZIfgWCsXN50uM
.youtube.com	TRUE	/	FALSE	1776819168	SID	g.a000uwg-dTwP1twnccQTKvS64x87qy2Q1UOqA_FnWnCbF9ZhBVnFcqrpJaYciaeBAU2Ar0bSWgACgYKAXASARISFQHGX2Mi1SbUer_CIFYD5uTv4nYN5xoVAUF8yKpuUHhMou9cT7cfAo_gfzxX0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1774742057	__Secure-1PSIDTS	sidts-CjEB7pHptWTCUpw2wfccG5MmeHPgBP2ANHuDrF9fcyQQ_L74sEEQg0JHymUm92cgqVCCEAA
.youtube.com	TRUE	/	TRUE	1776819168	SAPISID	3tAGfXqhQQDnNhSd/Av7bZIrm0OzMAKrnS
#HttpOnly_.youtube.com	TRUE	/	TRUE	1774742059	__Secure-1PSIDCC	AKEyXzWA1nPDOUPTwad2lmm2UAwmWAVfh5QXSYiyy4iZ_UWAsmaLJym2v7UjdslJHBxkEV5rqQ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1776819168	SSID	ARX8ONMIVh-qyOEps
.youtube.com	TRUE	/	TRUE	1776819168	__Secure-1PAPISID	3tAGfXqhQQDnNhSd/Av7bZIrm0OzMAKrnS
#HttpOnly_.youtube.com	TRUE	/	TRUE	1776819168	__Secure-1PSID	g.a000uwg-dTwP1twnccQTKvS64x87qy2Q1UOqA_FnWnCbF9ZhBVnF5SYhjH__rpuveJSmue3kgwACgYKAScSARISFQHGX2MiEasvPPsHnqEGVVPzny67zhoVAUF8yKqTbf9Tv3AuMOD3VX8154zE0076
.youtube.com	TRUE	/	TRUE	1776819168	__Secure-3PAPISID	3tAGfXqhQQDnNhSd/Av7bZIrm0OzMAKrnS
#HttpOnly_.youtube.com	TRUE	/	TRUE	1774742059	__Secure-3PSIDCC	AKEyXzVa3bBn0aCm8MSRz0H3I5LW1eM5k_RxwfbyFcWvks8h1lMqljYFM2zu_5YYHxcsMWk49Q
#HttpOnly_.youtube.com	TRUE	/	TRUE	1774742057	__Secure-3PSIDTS	sidts-CjEB7pHptWTCUpw2wfccG5MmeHPgBP2ANHuDrF9fcyQQ_L74sEEQg0JHymUm92cgqVCCEAA
.youtube.com	TRUE	/	FALSE	1776818954	_ga	GA1.1.1680234222.1742258954
.youtube.com	TRUE	/	FALSE	1776819035	_ga_VCGEPY40VB	GS1.1.1742258954.1.1.1742259035.60.0.0
.youtube.com	TRUE	/	FALSE	1776819168	APISID	yfmbVQCIDOt7QUGJ/A5MuO4rpOHGRDq-rO
#HttpOnly_.youtube.com	TRUE	/	FALSE	1776819168	HSID	A70Mc5Dk3dfah3wXL
#HttpOnly_.youtube.com	TRUE	/	TRUE	1776818874	LOGIN_INFO	AFmmF2swRQIhAKQPonXNBJe0rqmRbGGT1peKAzexfIAbuAo37GgZ2LGTAiAdPomtKfHCpym9oLkdLGEnlDRC3cEs1o1laHEyYwDMtA:QUQ3MjNmeGxwUVB5am9LM3hSLUlhR3JzMHhhRVFjV3BIX1ZYeVlTYm9TMGxQZUhxeGliQXFxdlVNcmN2bTZabU9PaEJEVkZ4Z29hVWlnRXg5eXg2WGxxNVhZUUg3QnE3eVZ6MkRyYzF5SDljN3FaQ0h3dXBkeFVUSXhwQ09nY1ZJbmVxWlBQN2FiakFKQUc2UUozaERQTlROT1BwQmp0QkVR
#HttpOnly_.youtube.com	TRUE	/	TRUE	1758070094	NID	522=mtDow3SjlGldH0qvkK7GtGHxM1Ulfu-x7aZdexBNF1vDPbcSUyH-gj8RxAsSQ6pBwyfpL4jYlOedGcsNxSqt4VNPJFB3OWv8ufm2iLxFANbZw1nBhR7t4MFjOOr22U_HWr8ARn01OQOOrBjEBbA9ijV1fR8pwSnuwzFd93_N9hX0zHcUc4L7cppAf0KtSZPJ8Fa0Q89jHohG0naGYzfWkQ
.youtube.com	TRUE	/	TRUE	1777766048	PREF	f6=80&tz=Asia.Dhaka
"""

API_ID = int(getenv("API_ID", "7fc5b35692454973318b86481ab5eca3"))
API_HASH = getenv("API_HASH", "28239710")
BOT_TOKEN = getenv("BOT_TOKEN", "8019809817:AAHN9iPbP2MNZXsOHK9inNi04DQx8hk0uE4")
OWNER_ID = list(map(int, getenv("OWNER_ID", "7303810912").split()))
MONGO_DB = getenv("MONGO_DB", "mongodb+srv://ytpremium4434360:zxx1VPDzGW96Nxm3@itssmarttoolbot.dhsl4.mongodb.net/?retryWrites=true&w=majority&appName=ItsSmartToolBot")
LOG_GROUP = getenv("LOG_GROUP", "-1001641417356")
CHANNEL_ID = int(getenv("CHANNEL_ID", "-1002399634158"))
FREEMIUM_LIMIT = int(getenv("FREEMIUM_LIMIT", "0"))
PREMIUM_LIMIT = int(getenv("PREMIUM_LIMIT", "500"))
WEBSITE_URL = getenv("WEBSITE_URL", "upshrink.com")
AD_API = getenv("AD_API", "52b4a2cf4687d81e7d3f8f2b7bc2943f618e78cb")
STRING = getenv("STRING", None)
YT_COOKIES = getenv("YT_COOKIES", YTUB_COOKIES)
DEFAULT_SESSION = getenv("DEFAUL_SESSION", None)  # added old method of invite link joining
INSTA_COOKIES = getenv("INSTA_COOKIES", INST_COOKIES)
